# Generated by Django 4.1.4 on 2023-02-04 18:31

from django.db import migrations, models
import testapp.manager


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=500, null=True)),
                ('forget_password', models.CharField(blank=True, max_length=500, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('objects', testapp.manager.UserManager()),
            ],
        ),
    ]
